FROM golang:1.22.7-alpine3.20 AS fetcher

RUN apk --no-cache add ca-certificates git

WORKDIR /tmp/sql-data/

COPY go.mod ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 go build -o dafr ./cmd/data-fetcher && ./dafr -d mysql

FROM mysql

COPY ./database/mysql/script.sh /docker-entrypoint-initdb.d/script01.sh
COPY --from=fetcher /tmp/sql-data/insert.sh /docker-entrypoint-initdb.d/script02.sh
RUN chown mysql:mysql /docker-entrypoint-initdb.d/*.sh && chmod 770 /docker-entrypoint-initdb.d/*.sh
