services:
  mysql-db:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.mysql
    env_file:
      - .env
    expose:
      - 3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --silent
      interval: 5s
      retries: 3
      start_period: 0s
      timeout: 3s
    ports:
      - 3306:3306
    restart: always

  server:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile
    command: ["./zipcodes", "-d", "mysql"]
    depends_on:
      mysql-db:
        condition: service_healthy
    expose:
      - 20790
    ports:
        - 20790:20790
    restart: always
