services:
  mysql-db:
    build:
      dockerfile: Dockerfile.mysql
    env_file:
      - mysql.env
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: always

  server:
    build:
      dockerfile: Dockerfile
    depends_on:
      mysql-db:
        condition: service_started
        required: true
    expose:
      - 20790
    ports:
        - 8080:20790
    restart: always
