#/bin/bash

SQL=$(cat <<-EOF
DROP DATABASE IF EXISTS $MYSQL_DATABASE;
CREATE DATABASE $MYSQL_DATABASE;
USE $MYSQL_DATABASE;

DROP TABLE IF EXISTS $MYSQL_TABLE;
CREATE TABLE $MYSQL_TABLE(
    id         INTEGER AUTO_INCREMENT NOT NULL,
    state_fips CHAR(2) NOT NULL,
    state      VARCHAR(25) NOT NULL,
    state_abbr CHAR(2) NOT NULL,
    zipcode    VARCHAR(7) NOT NULL,
    county     VARCHAR(50) NOT NULL,
    city       VARCHAR(35) NOT NULL,
    PRIMARY KEY (id)
);
EOF
)

mysql -u$MYSQL_USER -p$MYSQL_PASSWORD --init-command="$SQL"